#!/usr/bin/env python3
"""
gen_verification_index.py -- build book/verification/ltspice_index.html,
a single landing page linking to all per-chapter ltspice_chapterNN.html
verification pages (generated by gen_verification_html.py).

Usage: gen_verification_index.py
Reads every book/figures/ltspice/tools/chapterNN_spec.json it finds and
lists the circuits it contains as a one-line summary under a link to that
chapter's own verification page.
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[4]
TOOLS_DIR = REPO / "book" / "figures" / "ltspice" / "tools"
VERIFY_DIR = REPO / "book" / "verification"

CHAPTER_TITLES = {
    "01": "半導体の物理",
    "02": "パワー半導体の動作原理",
    "03": "デバイス特性とデバイス選択",
    "04": "リアクティブ素子とエネルギー",
    "05": "直流-直流変換(1) 非絶縁型",
    "06": "直流-直流変換(2) 絶縁型",
    "07": "直流-直流変換(3) リニアレギュレータ",
    "08": "交流-直流変換 整流回路",
    "09": "直流-交流変換 インバータ",
    "10": "交流-交流変換",
    "11": "電力変換で生じる電磁ノイズとEMC",
}

STYLE = """
body { font-family: "Hiragino Sans", "Noto Sans JP", sans-serif; background:#fff; color:#222; margin:2em auto; max-width: 880px; padding: 0 1em; }
h1 { border-bottom: 3px solid #0891b2; padding-bottom: 0.3em; }
table { border-collapse: collapse; width: 100%; margin-top: 1.5em; }
th, td { text-align: left; padding: 0.6em 0.8em; border-bottom: 1px solid #eee; vertical-align: top; }
th { color:#0e7490; border-bottom: 2px solid #0891b2; }
tr:hover { background:#f8fdff; }
.count { color:#555; font-size:0.85em; }
a { color:#0e7490; text-decoration: none; font-weight: bold; }
a:hover { text-decoration: underline; }
.meta { color:#555; font-size:0.95em; }
"""


def main():
    rows = []
    total_circuits = 0
    for num in sorted(CHAPTER_TITLES):
        spec_path = TOOLS_DIR / f"chapter{num}_spec.json"
        if not spec_path.exists():
            continue
        circuits = json.loads(spec_path.read_text(encoding="utf-8"))
        total_circuits += len(circuits)
        labels = "、".join(c["label"].split("(")[0].strip() for c in circuits)
        rows.append(
            f"<tr><td>第{int(num)}章</td>"
            f"<td><a href='ltspice_chapter{num}.html'>{CHAPTER_TITLES[num]}</a></td>"
            f"<td class='meta'>{labels}</td>"
            f"<td class='count'>{len(circuits)}回路</td></tr>"
        )

    html = "\n".join([
        "<!DOCTYPE html><html lang='ja'><head><meta charset='utf-8'>",
        "<title>LTspice検証記録 -- 全章インデックス</title>",
        f"<style>{STYLE}</style></head><body>",
        "<h1>LTspice検証記録 -- 全章インデックス</h1>",
        "<p class='meta'>教科書『パワーエレクトロニクス』の各章末問題のうち"
        "【LTspiceで確かめよ】と明示された回路を、ngspiceで実測し本文の数値・式と"
        "突き合わせた補助資料一覧。既存の本文・掲載図(fig*.eps)は変更していない。"
        "各章の詳細（ネットリスト・SVG・VERIFICATION_NOTES.mdの検証根拠）は"
        "リンク先および book/figures/ltspice/chapterNN/ を参照。</p>",
        f"<p class='meta'>全{len(rows)}章 / 全{total_circuits}回路</p>",
        "<table><tr><th>章</th><th>タイトル</th><th>回路</th><th></th></tr>",
        "\n".join(rows),
        "</table>",
        "</body></html>",
    ])
    out = VERIFY_DIR / "ltspice_index.html"
    out.write_text(html, encoding="utf-8")
    print(f"written: {out} ({len(rows)} chapters, {total_circuits} circuits)")


if __name__ == "__main__":
    main()
